# Ubicado en: directorio/netlify.toml

[build]
  base = "directorio"
  publish = "public"
  functions = "netlify/functions"

[functions]
  # CORRECCIÓN: Apunta a la ruta exacta del archivo desde la raíz del repo.
  included_files = ["directorio/netlify/functions/files/directorio.xlsx"]
