# netlify.toml
# Este archivo debe estar en la RAÍZ de tu repositorio.

[build]
  # No hay 'base', porque el proyecto ya está en la raíz.
  publish = "public"
  functions = "netlify/functions"

[functions]
  # La ruta es desde la raíz del repositorio.
  included_files = ["netlify/functions/files/directorio.xlsx"]
