# netlify.toml

# Configuración principal de construcción
[build]
  # 1. Directorio Base: Le dice a Netlify que primero entre a la carpeta 'directorio'.
  base = "directorio"
  
  # 2. Directorio de Publicación: La carpeta a publicar, relativa al 'base'.
  publish = "public"
  
  # 3. Directorio de Funciones: Relativo al 'base'.
  functions = "netlify/functions"

# Configuración de las funciones
[functions]
  # 4. Archivos Incluidos: La ruta debe ser desde la RAÍZ del repositorio.
  included_files = ["directorio/netlify/functions/directorio.xlsx"]

# Opcional pero recomendado: Fija la versión de Python.
[functions.python]
  runtime = "python3.11"
