# netlify.toml

# Como el "Base directory" ya está configurado en la web de Netlify,
# este archivo solo necesita especificar lo que está adentro.

[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  # La ruta a los archivos incluidos debe ser desde la raíz de tu repositorio
  included_files = ["directorio-web-netlify/netlify/functions/directorio.xlsx"]

[functions.python]
  runtime = "python3.11"
