# netlify.toml

[build]
  publish = "public"
  functions = "netlify/functions"

# --- AÑADIR ESTA SECCIÓN ---
[functions]
  # Esto le dice a Netlify que incluya el archivo Excel en el despliegue de la función.
  # La ruta es desde la raíz de tu proyecto.
  included_files = ["netlify/functions/directorio.xlsx"]
