[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  # La ruta debe ser desde la raíz de la carpeta base ('directorio')
  included_files = ["netlify/functions/directorio.xlsx"]

# --- AÑADIR ESTO PARA DEFINIR LA VERSIÓN DE PYTHON ---
[functions.python]
  runtime = "python3.11"
