# Este archivo está en la carpeta 'directorio'

[build]
  # El directorio a publicar, relativo a la ubicación de este toml.
  publish = "public"
  
  # El directorio de funciones, relativo a la ubicación de este toml.
  functions = "netlify/functions"

[functions]
  # La ruta a los archivos incluidos es desde la RAÍZ del repositorio.
  included_files = ["directorio/netlify/functions/directorio.xlsx"]

# Opcional pero recomendado: Fija la versión de Python.
[functions.python]
  runtime = "python3.11"
